/*

 LOGO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 9
   Tile set      : C:\Users\Kotone\Documents\gbtd22\logo.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 36
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tempLogoWidth 10
#define tempLogoHeight 9
#define tempLogoBank 0

extern unsigned char tempLogo[];

/* End of LOGO.H */
